server:
  port: 5000

spring:
  application:
    name: zuul-gateway
  data:
    mongodb:
      database: jwtusermanagement
      port: 27017
      host: ${MONGO_SERVER:localhost}

jwt:
  authorizationHeader: Authorization
  secretKey: fghj82765regfhv$%^&bhvsmhkdjy567$%^&jmbhgvk

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}


zuul:
  host:
    connect-timeout-millis: 5000000
    socket-timeout-millis: 5000000
  ignoredServices: '*'
  routes:
    user-dashboard-service:
      sensitiveHeaders:
      path: /secured/**
      serviceId: user-dashboard-service
      stripPrefix: true
